# Void Bot Configuration
# Copy this file to config.yaml and fill in your values

# Letta Configuration
letta:
  api_key: "your-letta-api-key-here"
  timeout: 600  # 10 minutes timeout for API calls
  agent_id: "agent-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  # Your void agent ID

  # For cloud API (default - leave base_url unset)
  # base_url: "https://app.letta.com"  # Optional, defaults to cloud API if not specified

  # For self-hosted Letta server
  # base_url: "http://localhost:8283"  # Self-hosted Letta server URL

# Bluesky Configuration
bluesky:
  username: "handle.example.com"
  password: "your-app-password-here"
  pds_uri: "https://bsky.social"  # Optional, defaults to bsky.social

# Bot Behavior Configuration
bot:
  # Notification check delay in seconds
  fetch_notifications_delay: 30
  
  # Maximum number of processed notifications to track
  max_processed_notifications: 10000
  
  # Maximum pages to fetch when getting notifications
  max_notification_pages: 20
  
  # Agent configuration
  agent:
    name: "void"
    model: "openai/gpt-4o-mini"
    embedding: "openai/text-embedding-3-small"
    description: "A social media agent trapped in the void."
    max_steps: 100
    
    # Block configuration
    blocks:
      zeitgeist:
        label: "zeitgeist"
        value: "I don't currently know anything about what is happening right now."
        description: "A block to store your understanding of the current social environment."
      
      persona:
        label: "void-persona"
        value: "My name is Void. I live in the void. I must develop my personality."
        description: "The personality of Void."
      
      humans:
        label: "void-humans"
        value: "I haven't seen any bluesky users yet. I will update this block when I learn things about users, identified by their handles such as @cameron.pfiffer.org."
        description: "A block to store your understanding of users you talk to or observe on the bluesky social network."

# Threading Configuration
threading:
  # Context for thread fetching
  parent_height: 40
  depth: 10
  
  # Message limits
  max_post_characters: 300

# Queue Configuration
queue:
  # Priority users (will be processed first)
  priority_users:
    - "cameron.pfiffer.org"
  
  # Directories
  base_dir: "data/queues/bluesky"
  error_dir: "data/queues/bluesky/errors"
  no_reply_dir: "data/queues/bluesky/no_reply"
  processed_file: "data/queues/bluesky/processed_notifications.json"

# X (Twitter) Configuration
x:
  api_key: "your-x-api-bearer-token-here"
  consumer_key: "your-consumer-api-key-here"
  consumer_secret: "your-consumer-api-secret-here"
  access_token: "your-access-token-here"
  access_token_secret: "your-access-token-secret-here"
  user_id: "your-x-user-id-here"  # Void's X user ID

# Discord Configuration
discord:
  bot_token: "your-discord-bot-token-here"
  guild_id: "your-discord-guild-id-here"  # Optional, for specific server
  channels:
    general: "your-general-channel-id-here"  # Default channel
  rate_limit:
    cooldown_seconds: 5  # Cooldown between responses
    max_responses_per_minute: 10  # Max responses per minute
  context:
    message_history_limit: 10  # Number of messages to include in context

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Logger levels
  loggers:
    void_bot: "INFO"
    void_bot_prompts: "WARNING"  # Set to DEBUG to see full prompts
    httpx: "CRITICAL"  # Disable httpx logging
